[package]
name = "runner"
version = "0.1.1"
edition = "2024"

[dependencies]
core = { workspace = true }
util = { workspace = true }
graph-lib = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
itertools = "0.14"
tokio = { version = "1", features = ["sync", "rt", "fs"] }
parquet = { version = "55.0", features = ["async"] }
arrow-array = "55.0"
toml = "0.8"
anyhow = { workspace = true }
clap = { workspace = true }